name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
        
      - name: Build
        run: |
           xcodebuild clean build -workspace "NewsForYou/NewsForYou.xcworkspace" -scheme "NewsForYou" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Test
        run: |
           xcodebuild clean test -workspace "NewsForYou/NewsForYou.xcworkspace" -scheme "NewsForYouTests" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO 
           
